version: '3.8'
services:
  app:
    build: .
    container_name: express-wa-forwarder
    restart: always
    env_file:
      - .env
    ports:
      - "2208:2208"
    volumes:
      - ./.wwebjs_auth:/usr/src/app/.wwebjs_auth
